### ISSUE TITLE
Touch screen Y axis seems to be inverted

### ISSUE THREAD

**Issue by DullPointer** [mikahjc/3dsRemapBuilder#14]
Hello, thanks for your great work building this useful site!

I had an issue with the touch mapping and I believe that it is caused by the Y axis being inverted compared to the [guide image](https://gbatemp.net/threads/wip-rehid-button-remapping-for-3ds.585387/page-4#post-9421964) that I have successfully used before.

Would you be able to investigate and update this if need be? Thanks very much.

**Comment by mikahjc** [comment]
Just looked, and it does seem backwards vs how rehid is set up. I can look at fixing that shortly.

**Comment by mikahjc** [comment]
@DullPointer I just pushed an update that should fix this, can you verify?

**Comment by DullPointer** [comment]
Unfortunately that hasn't fixed it. I now end up with a negative value on the X axis that is invalid instead.

**Comment by mikahjc** [comment]
That's because I'm an idiot and fixed the X coordinate as if it were the Y coordinate. Just pushed code that should actually fix it, verify please?

**Comment by DullPointer** [comment]
Ahah, oops! Well it's working perfectly now so I'll close this off. Thank you very much for the fix!
